Portfolio: add a contact form and finish the mobile version
K0ppai/portfolio pull request #4
Opened 2023-05-02 14:58 UTC by K0ppai

2023-05-02 15:03 UTC, bobb-Rob reviewed
Hi @K0ppai, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that lacks commits from your pair programming partner. Please ensure your coding partner(s) make significant contributions to this project. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-05-02 18:33 UTC, stanleySimeon requested changes
# Hi @K0ppai 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# ⚠️ Invalid Code Review Request ⚠️ 

As mentioned by the previous reviewer, you have submitted a project, that lacks commits from your pair programming partner. Please ensure your coding partner(s) make significant contributions to this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @stanleySimeon in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-02 18:33 UTC, stanleySimeon commented on index.html
> +        <button type="submit">Get in touch</button>
Kindly I suggest you implement the button interactions (enable, hover, etc.) to make your design match the requirements and be more professional. 😄

2023-05-02 18:33 UTC, stanleySimeon commented on index.html
> +
Kindly I suggest removing all unnecessary white lines in your project to make it more professional and to HTML best practices. 😄

2023-05-02 18:33 UTC, stanleySimeon commented on index.html
> +        </ul>
Kindly I suggest you follow the [Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48-988&t=K9cgnTJBB99smpxE-0) template to make the footer as it is. 😄 

>### The Figma Design
>
><img width="363" alt="Screenshot 2023-05-02 at 14 24 06" src="https://user-images.githubusercontent.com/91237525/235752636-3044b93c-afe0-43f4-a04c-394526d6eb33.png">
>
>### Your Design
>
><img width="304" alt="Screenshot 2023-05-02 at 14 24 50" src="https://user-images.githubusercontent.com/91237525/235752791-326486d7-4527-40a7-a146-74af67ce0d67.png">

- [ ] Kindly make sure you add the bottom bar to follow the design

2023-05-02 18:33 UTC, stanleySimeon commented on style.css
> +  /* align-content: center; */
I suggest you remove the commented code in your code base to follow best practices.
Please note by following this, your project will look more professional. 😄

2023-05-03 03:17 UTC, shella12 reviewed
Hi @K0ppai , 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [ ] is a pair programming project with no contribution from partner. Kindly make sure your partner contributes some code into your codebse.
- [ ] Also please remove` Note` from the LICENCE section of the README. `Note `is there in the template to guide you on how you to add a LICENCE to your README. Once you have successfully added the LICENCE you can go ahead and remove it


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-03 03:29 UTC, shella12 reviewed
Hi @K0ppai, 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project, that **is a [pair-programming activity](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#work-and-submission-mode). Please make sure everyone of your partners have contributed to the project before submitting for another request.**

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-03 03:32 UTC, stanleySimeon commented
> Hi @K0ppai,
> 
> # Status: Invalidated 🔴
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> ### You have submitted a project, that **is a [pair-programming activity](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#work-and-submission-mode). Please make sure everyone of your partners have contributed to the project before submitting for another request.**
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-03 03:33 UTC, stanleySimeon commented
This student works solely on this project, kindly don't invalidate!

2023-05-03 03:49 UTC, stanleySimeon approved these changes
# Hi @K0ppai

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# Status: Approved 🎉 

![](https://media4.giphy.com/media/YKdm91XONLTaw/giphy-downsized.gif?cid=29caca75xin3l5kzm3xxnx15oi4v91qw6zswtoa7n8hkl8rd&ep=v1_gifs_search&rid=giphy-downsized.gif&ct=g)

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 03:52 UTC, merged